# Generated by Django 5.0.2 on 2024-03-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='modified',
            new_name='updated_at',
        ),
    ]
