# Generated by Django 5.0.2 on 2024-03-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_created_document_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
    ]
